# Generated by Django 6.0.7 on 2026-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
