# Generated by Django 6.0.7 on 2026-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GST', models.IntegerField(default=18)),
                ('Delivery_Charge', models.IntegerField(default=50)),
                ('Rain_Charge', models.IntegerField(default=20)),
                ('Small_Cart_Charge', models.IntegerField(default=30)),
            ],
        ),
    ]
